apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [agent]
      debug = true
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      quiet = false
      logfile = ""
      hostname = ""
      omit_hostname = false
    
    [[outputs.postgresql]]
      connection = "$TS_PG_CONN"
      namepass = ["data"]
      schema = "public"
      timestamp_column_name = "time"
    
    [[processors.enum]]
      tagpass = { source = ["http"] }
    
      [[processors.enum.mapping]]
        tags = ["device"]
        dest = "device"
        default = "unknown"
    
        [processors.enum.mapping.value_mappings]
          "E8DB84071451" = "hermon-00"
          "E8DB84079EE5" = "hermon-05"
    
    [[processors.enum]]
      tagpass = { topic = ["*"] }
    
      [[processors.enum.mapping]]
        tags = ["topic"]
        dest = "device"
        default = "unknown"
    
        [processors.enum.mapping.value_mappings]
          "helium/06f3f63b-cfed-4512-a59b-640978050191/rx" = "hermon-00"
          "helium/340bc295-28f0-4cea-b917-e37e6a3ff036/rx" = "hermon-01"
          "helium/8017cbd5-6b5f-4062-8893-df928110d234/rx" = "hermon-02"
          "helium/077d3404-7c47-4f27-b269-d455a554b932/rx" = "hermon-03"
          "helium/f41a4e1b-e3f2-42b7-bb18-7a63aed63a0f/rx" = "hermon-04"
          "helium/579dfef4-00c8-4dec-998a-c550b1406b8e/rx" = "hermon-05"
          "helium/a88449c9-c499-4490-a191-612e0c922f56/rx" = "hermon-06"
          "helium/307ff6c7-4649-43e1-9b12-d81feb730514/rx" = "hermon-07"
          "helium/d40378af-8159-4bd8-a6f3-1c7a459b3f0b/rx" = "hermon-08"
          "helium/88f845f5-0853-427b-9665-2116bab377dc/rx" = "hermon-09"
    
          "helium/hermon/917c0107-a735-4e6b-bd7e-4b68ec630e55/rx" = "hermon-00"
          "helium/hermon/39056fc1-082a-4d21-b65a-297b5f4ca0e5/rx" = "hermon-01"
          "helium/hermon/23084830-9996-4305-9b55-3915aceb4a12/rx" = "hermon-02"
          "helium/hermon/bf205f49-5fa4-47a9-b659-e0a5704b4b53/rx" = "hermon-03"
          "helium/hermon/9064de15-ac39-477b-b4d5-91a077924b92/rx" = "hermon-04"
          "helium/hermon/a485e50d-54f2-4d96-b451-57ec0523d6f8/rx" = "hermon-05"
          "helium/hermon/783619ca-7d23-41f1-becb-459296a7357a/rx" = "hermon-06"
          "helium/hermon/5a010f67-28a8-4a47-9239-b5c839a9329e/rx" = "hermon-07"
          "helium/hermon/e666166a-66a6-4b66-83f3-691f4136551f/rx" = "hermon-08"
          "helium/hermon/98e8e467-fa92-427c-ae88-c14dbd5a5ac2/rx" = "hermon-09"
    
          "v3/hermon@ttn/devices/hermon-09/up" = "hermon-09"
    
          "helium/hermon/curl-device/rx" = "hermon-curl"
          "helium/hermon/simulator/rx" = "hermon-simulator"
          "helium/AAAA-AAAA-AAAA-AAAA/rx" = "test-device"
          "kudzutestdevice/rx" = "test"
          "new_kudzutestdevice/rx" = "test"
    
          "helium/hermon/hermonhttp/rx" = "hermon-http"
          "helium/hermon/hermonhttphome/rx" = "hermon-http-home"
          "helium/hermon/hermonhttpoffice/rx" = "hermon-http-office"
          "helium/hermon/hermonhttppavlos/rx" = "hermon-http-pavlos"
          "helium/hermon/hermon00/rx" = "hermon-00"
    
          "helium/hermon/E8DB84079DBD/rx" = "hermon-http-office"
          "helium/hermon/E8DB840712E9/rx" = "hermon-http-home"
          "helium/hermon/E8DB84071451/rx" = "hermon-00"
          "helium/hermon/E8DB84079EE5/rx" = "hermon-05"
    
    [[inputs.http_listener_v2]]
      name_override = "data"
      service_address = ":5001"
      paths = ["/telegraf"]
      methods = ["POST"]
      data_format = "json"
      tag_keys = ["device"]
    
      [inputs.http_listener_v2.tags]
        source = "http"
    
    [[inputs.mqtt_consumer]]
      name_override = "data"
      servers = ["tcp://broker.hivemq.com:1883"]
      qos = 0
      connection_timeout = "30s"
      persistent_session = false
      client_id = "trackplast-helium"
    
      topics = [
        "helium/hermon/917c0107-a735-4e6b-bd7e-4b68ec630e55/#",
        "helium/hermon/39056fc1-082a-4d21-b65a-297b5f4ca0e5/#",
        "helium/hermon/23084830-9996-4305-9b55-3915aceb4a12/#",
        "helium/hermon/bf205f49-5fa4-47a9-b659-e0a5704b4b53/#",
        "helium/hermon/9064de15-ac39-477b-b4d5-91a077924b92/#",
        "helium/hermon/a485e50d-54f2-4d96-b451-57ec0523d6f8/#",
        "helium/hermon/783619ca-7d23-41f1-becb-459296a7357a/#",
        "helium/hermon/5a010f67-28a8-4a47-9239-b5c839a9329e/#",
        "helium/hermon/e666166a-66a6-4b66-83f3-691f4136551f/#",
        "helium/hermon/98e8e467-fa92-427c-ae88-c14dbd5a5ac2/#",
    
        "helium/hermon/ed316143-d52b-4977-88c7-af0264e19ae3/#",
        "helium/hermon/a8ec95f0-6dd6-4cac-ac57-34559f973220/#",
        "helium/hermon/f4285555-ec96-400b-88fb-159d48c52a78/#",
    
        "helium/06f3f63b-cfed-4512-a59b-640978050191/#",
        "helium/340bc295-28f0-4cea-b917-e37e6a3ff036/#",
        "helium/8017cbd5-6b5f-4062-8893-df928110d234/#",
        "helium/077d3404-7c47-4f27-b269-d455a554b932/#",
        "helium/f41a4e1b-e3f2-42b7-bb18-7a63aed63a0f/#",
        "helium/579dfef4-00c8-4dec-998a-c550b1406b8e/#",
        "helium/a88449c9-c499-4490-a191-612e0c922f56/#",
        "helium/307ff6c7-4649-43e1-9b12-d81feb730514/#",
        "helium/d40378af-8159-4bd8-a6f3-1c7a459b3f0b/#",
        "helium/88f845f5-0853-427b-9665-2116bab377dc/#",
    
        "kudzutestdevice/#",
        "new_kudzutestdevice/#",
    
        "helium/hermon/hermonhttp/#",
        "helium/hermon/hermonhttphome/#",
        "helium/hermon/hermonhttpoffice/#",
        "helium/hermon/hermonhttppavlos/#",
    
        "helium/hermon/curl-device/#",
        "helium/hermon/simulator/#"
      ]
    
      data_format = "json"
    
      [inputs.mqtt_consumer.tags]
        source = "mqtt"
    
    [[inputs.mqtt_consumer]]
      name_override = "data"
      servers = ["tcp://eu1.cloud.thethings.network:1883"]
      qos = 0
      connection_timeout = "30s"
      persistent_session = false
      client_id = "hermon-ttn"
      username = "$TTN_USERNAME"
      password = "$TTN_PASSWORD"
    
      topics = ["v3/hermon@ttn/devices/+/up"]
      data_format = "json_v2"
    
      [inputs.mqtt_consumer.tags]
        source = "mqtt"
    
      [[inputs.mqtt_consumer.json_v2]]
        timestamp_path = "received_at"
        timestamp_format = "2006-01-02T15:04:05.999999999Z07:00"
    
        [[inputs.mqtt_consumer.json_v2.tag]]
          path = "end_device_ids.device_id"
          rename = "device"
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.battery"
          rename = "decoded_payload_battery"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_analog_input_0"
          rename = "decoded_payload_hermon_analog_input_0"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_analog_input_1"
          rename = "decoded_payload_hermon_analog_input_1"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_analog_input_2"
          rename = "decoded_payload_hermon_analog_input_2"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_analog_input_3"
          rename = "decoded_payload_hermon_analog_input_3"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_0.x"
          rename = "decoded_payload_hermon_accelerometer_0_x"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_0.y"
          rename = "decoded_payload_hermon_accelerometer_0_y"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_0.z"
          rename = "decoded_payload_hermon_accelerometer_0_z"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_1.x"
          rename = "decoded_payload_hermon_accelerometer_1_x"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_1.y"
          rename = "decoded_payload_hermon_accelerometer_1_y"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_1.z"
          rename = "decoded_payload_hermon_accelerometer_1_z"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_2.x"
          rename = "decoded_payload_hermon_accelerometer_2_x"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_2.y"
          rename = "decoded_payload_hermon_accelerometer_2_y"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_2.z"
          rename = "decoded_payload_hermon_accelerometer_2_z"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_3.x"
          rename = "decoded_payload_hermon_accelerometer_3_x"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_3.y"
          rename = "decoded_payload_hermon_accelerometer_3_y"
          type = "float"
          optional = true
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_accelerometer_3.z"
          rename = "decoded_payload_hermon_accelerometer_3_z"
          type = "float"
          optional = true
    
        [[inputs.mqtt_consumer.json_v2.field]]
          path = "uplink_message.decoded_payload.hermon_digital_input_127"
          rename = "decoded_payload_hermon_digital_input_127"
          type = "int"
          optional = true
