apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf@sha256:d1a485308163ea51f8a07b659a71cba8e1eddcaf8473a25c00e34e363e8b3775
          imagePullPolicy: IfNotPresent
          command:
            - telegraf
          args:
            - --config
            - /etc/telegraf/telegraf.conf
          env:
            - name: TS_PG_CONN
              valueFrom:
                secretKeyRef:
                  name: telegraf-db-secret
                  key: TS_PG_CONN
            - name: TTN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf-ttn-secret
                  key: TTN_USERNAME
            - name: TTN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-ttn-secret
                  key: TTN_PASSWORD
          ports:
            - containerPort: 5001
              name: http
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
