apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: telegraf-config-base
    files:
      - assets/telegraf.conf

  - name: telegraf-config-mqtt-public
    files:
      - assets/conf.available/inputs-mqtt-public.conf

  - name: telegraf-config-mqtt-ttn
    files:
      - assets/conf.available/inputs-mqtt-ttn.conf
