apiVersion: 1

datasources:
  - name: Hermon Timescale
    uid: hermon-timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: $GRAFANA_DB_USER
    isDefault: true
    editable: false
    jsonData:
      database: $GRAFANA_DB_NAME
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
